# https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions001.htm
types:
  boolean: BOOLEAN
  integer: INTEGER
  decimal: DECIMAL(10,4)
  string: VARCHAR({0})
  dateTime: DATETIME
  date: DATE
  time: TIME
format:
  dateTime: 'yyyy-LL-dd HH:mm:ss'
  date: 'yyyy-LL-dd'
  time: 'HH:mm:ss'  
ddl:  
  createDatabase: 'CREATE DATABASE IF NOT EXISTS {name}'
  createEntity: 'CREATE TABLE {name} ({define})'
  createSequence: 'CREATE SEQUENCE {name} START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999 MINVALUE 1'
  incrementalColumDefine: '{name} {type} {required} AUTO_INCREMENT' 
  columnDefine: '{name} {type} {required} '
  createPk: 'CONSTRAINT {name} PRIMARY KEY ({columns})'
  createUk: 'CONSTRAINT {name} UNIQUE ({columns})' 
  createFk: 'CONSTRAINT {name} FOREIGN KEY ({column}) REFERENCES {fTable} ({fColumn})'  
  createIndex: 'CREATE INDEX {name} ON {table} ({columns})'
  alterTable: 'ALTER TABLE {name}'
  addProperty: 'ADD {columnDefine}'
  addPk: 'ADD CONSTRAINT {name} PRIMARY KEY ({columns})'
  addUk: 'ADD CONSTRAINT {name} UNIQUE ({columns})'
  addFk: 'ADD CONSTRAINT {name} FOREIGN KEY ({column}) REFERENCES {fTable} ({fColumn})'
  alterProperty: 'MODIFY {columnDefine}'
  dropDatabase: 'DROP DATABASE IF EXISTS {name}'
  dropEntity: 'DROP TABLE IF EXISTS {name}'
  dropSequence: 'DROP SEQUENCE {name}'
  dropProperty: 'DROP COLUMN {name}'
  dropPk: 'DROP PRIMARY KEY {name}'
  dropUk: 'DROP UNIQUE {name}'
  dropFk: 'DROP FOREIGN KEY {name}'
  dropIndex: 'DROP INDEX {name} ON {table}'
  truncateEntity: 'TRUNCATE TABLE {name}'
dml:
  map: SELECT {0}
  select: SELECT {0}
  distinct: SELECT DISTINCT {0}
  filter: WHERE {0}
  where: WHERE {0}
  groupBy: GROUP BY {0}
  having: HAVING {0}
  sort: ORDER BY {0}
  order: ORDER BY {0}
  page: "{sentence} LIMIT {offset},{records}" 
  insert: INSERT INTO {name}({fields}) VALUES({values})
  update: UPDATE {name} {alias} SET {assigns} 
  remove: DELETE FROM {name} {alias} 
  delete: DELETE FROM {name} {alias} 
  bulkInsert: INSERT INTO {name}({fields}) VALUES {values}  
  from: 'FROM {name} {alias} '
  join: 'INNER JOIN {name} {alias} ON {relation}'
others:
  delimiter: '"{name}"'
  separatorSql: ;
  notNullable: NOT NULL
  variable: ':{name}'
  field: '{entityAlias}.{name}'
  column: '{name}'  
  false: 'FALSE'
  true: 'TRUE'
  null: 'NULL'
  sequenceNextVal : '{name}.nextval'
  solveComposite: false
operators:
  unary:
    '-': '- {0}'
    '~': '~ {0}'
    '!': 'NOT {0}'
  binary:  
    '+': '({0} + {1})' 
    '-': '({0} - {1})'
    '*': '({0} * {1})'
    '/': '({0} / {1})'
    '**': 'POWER({0},{1})'
    '//': 'POWER({0},(1/{1}))'
    '%': MOD({0},{1})
    '&': '{0} & {1}'
    '|': '{0} | {1}'
    '^': '{0} ^ {1}'    
    '<<': '{0} << {1}'
    '>>': '{0} >> {1}'
    '==': '{0} = {1}'
    '===': '{0} = {1}'
    '!=': '{0} <> {1}'
    '!==': '{0} <> {1}'
    '>': '{0} > {1}'
    '<': '{0} < {1}'
    '>=': '{0} >= {1}'
    '<=': '{0} <= {1}'
    '&&': '({0} AND {1})'
    '||': '({0} OR {1})'
    '[]': 'N/A'
    '=': '{0} = {1}'
    '+=': '{0} = ({0} + {1})'
    '-=': '{0} = ({0} - {1})'
    '*=': '{0} = ({0} * {1})'
    '/=': '{0} = ({0} / {1})'
    '**=': '{0} = POWER({0},{1})'
    '//=': '{0} = POWER({0},(1/{1}))'
    '%=': '{0} = MOD({0},{1})'
    '&=': '{0} = {0} & {1} '
    '|=': '{0} = {0} | {1}'
    '^=': '{0} = {0} ^ {1}'
    '<<=': '{0} = {0} << {1}'
    '>>=': '{0} = {0} >> {1}'
  ternary:    
    '?': 'IF {0} THEN {1} ELSE {2} END'
functions:
  general:
    as: '{value} AS {alias}'
    desc: '{0} desc'
    asc: '{0} asc'
    between: '{0} BETWEEN {1} AND {2}'
    includes: ' {1} IN ({0})'
    contains: ' {1} IN ({0})'
    in: ' {0} IN ({1})'
    distinct: 'DISTINCT {0} '
  numeric:
    abs: 'ABS({0})'
    acos: 'ACOS({0})'
    asin: 'ASIN({0})'
    atan: 'ATAN({0})'
    atan2: 'ATAN2({0},{1})'
    ceil: 'CEIL({0})'
    cos: 'COS({0})'
    cosh: 'COSH({0})'
    exp: 'EXP({0})'
    floor: 'FLOOR({0})'
    ln: 'LN({0})'
    log10: 'LOG10({0})'
    log: 'LOG({0},{1})'
    remainder: 'REMAINDER({0},{1})'
    round: 'ROUND({0},{1})'
    sign: 'SIGN({0})'
    sin: 'SIN({0})'
    sinh: 'SINH({0})'
    tan: 'TAN({0})'
    tanh: 'TANH({0})'
    trunc: 'TRUNC({0},{1})'
    toNumber: 'CAST({0} AS NUMBER)'
  string:
    chr: 'CHR({0})'
    initcap: 'INITCAP({0})'
    lower: 'LOWER({0})'
    lpad: 'LPAD({0},{1},{2})'
    ltrim: 'LTRIM({0})'
    regExpReplace: 'REGEXP_REPLACE({0},{1})'
    regExpSubstr: 'REGEXP_SUBSTR({0},{1})'
    replace: 'REPLACE({0},{1},{2})'
    rpad: 'RPAD({0},{1},{2})'
    rtrim: 'RTRIM({0})'
    substr: 'SUBSTR({0},{1},{2})'
    substring: 'SUBSTR({0},{1},{2})'
    strCount: "(LENGTH({0})-LENGTH(REPLACE({0},{1},'')))"
    trim: 'TRIM({0})'
    upper: 'UPPER({0})'
    length: 'LENGTH({0})'
    mask: "Concat(LEFT({0},3),'***',RIGHT({0},3))"
    parse: 'json_value({0})'
    # stringify: 'JSON_OBJECT({0})'
    toString: 'CAST({0} AS VARCHAR2)'
  dateTime:
    # https://www.w3schools.com/jsref/jsref_obj_date.asp
    # https://phoenixnap.com/kb/mysql-date-function#ftoc-heading-8
    now: 'SYSTIMESTAMP'
    curTime: 'CAST(SYSTIMESTAMP AS TIME)'
    today: 'TRUNC(SYSDATE)'     
    dateTime: 'CAST({0} AS TIMESTAMP)'
    date: 'CAST({0} AS DATE)'
    time: 'CAST({0} AS TIME)'
    year: 'EXTRACT(YEAR FROM {0})'
    month: 'EXTRACT(MONTH FROM {0})'
    day: 'DAY(DAY FROM {0})'
    weekday: "TO_NUMBER(TO_CHAR({0}, 'D'))"
    hour: 'EXTRACT(HOUR FROM {0})'
    minute: 'EXTRACT(MINUTE FROM {0})'
    second: 'EXTRACT(SECOND FROM {0})'
    millisecond: 'EXTRACT(MILLISECOND FROM {0})'
    addYear: "{0} + interval '{1}' YEAR"
    addMonth: 'ADD_MONTHS({0},{1})'
    addDay: '{0} + {1}'
    addHour: "{0} + interval '{1}' HOUR"
    addMinute: "{0} + interval '{1}' MINUTE"
    addSecond: "{0} + interval '{1}' SECOND"
    addMillisecond: "{0} + interval '{1}' MILLISECOND"
    addTime: 'ADDTIME({0},{1})'
    subtractTime: 'SUBTIME({0},{1})'
    dayDiff: 'DATEDIFF({0},{1})'
    hourDiff: 'TIMESTAMPDIFF(HOUR,({0},{1})'
    secondDiff: 'TIMESTAMPDIFF(SECOND,({0},{1})'
    millisecondDiff: 'TIMESTAMPDIFF(MICROSECOND,({0},{1})'
    dayToDate: "DATE_FORMAT(FROM_UNIXTIME({0}*24*3600*1000), '%Y-%m-%dT%TZ')"
    hourToDate: "DATE_FORMAT(FROM_UNIXTIME({0}*3600*1000), '%Y-%m-%dT%TZ')"
    secondToDate: "DATE_FORMAT(FROM_UNIXTIME({0}*1000), '%Y-%m-%dT%TZ')"
    millisecondToDate: "DATE_FORMAT(FROM_UNIXTIME({0}), '%Y-%m-%dT%TZ')"
    dateToString: TO_CHAR({0},'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM')
  metadata:
    user: 'USER'
    source: "SYS_CONTEXT('USERENV','DB_NAME')"   
  null:
    nvl: 'NVL({0},{1})'
    nvl2: 'NVL2({0},{1},{2})' 
    isNull: '({0} IS NULL)' 
    isNotNull: '({0} IS NOT NULL)' 
  multiple:
    concat: '{accumulated} || {value}'
  group:    
    avg: AVG({0})
    count: COUNT({0})
    first: FIRST({0})
    last: LAST({0})
    max: MAX({0})
    min: MIN({0})
    sum: SUM({0})


  