default:
  livenessProbe:
    httpGet:
      path: /health
      port: ${port}
    initialDelaySeconds: 5
  periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /health
      port: ${port}
    initialDelaySeconds: 5
    periodSeconds: 20