mappings:
  - name: default
    entities:
      # Abstracts 
      - name: Basics
        abstract: true
        properties:
          - name: created
            mapping: created
          - name: createdBy
            mapping: created_by
  - name: oracle
    extends: default
