sequence:
  type: random
  shapes: LTSZJOI
  speedMin: 1
  speedMax: 5
screen:
  pixelSize: 32
  cols: 10
  rows: 20
shapes:
  - name: I
    color: cyan
    shape: |
      #
      #
      #
      #
  - name: J
    color: blue
    shape: |
      -#
      -#
      ## 
  - name: L
    color: orange
    shape: |
      #-
      #-
      ##                          
  - name: O
    color: yellow
    shape: |
      ##
      ##         
  - name: S
    color: green
    shape: |
      -##
      ##-
  - name: T
    color: purple
    shape: |
      ###
      -#-
  - name: Z
    color: red
    shape: |
      ##-
      -##   
