clusterIP:
  apiVersion: v1
  kind: Service
  metadata:
    name: ${name}
    namespace: ${namespace}
    labels:
      app: ${name}
  spec:
    ports:
    - name: http
      port: ${port}
      protocol: TCP
      targetPort: ${port}
    selector:
      app: ${name}
    type: ClusterIP