3-4: 
  _extends: [base,screen.normal]
  age:
    from : 3
    to : 4
  ghost:
    quantity: 0
    speed:
      from: 1
      to: 2
5-6:      
  _extends: [base,screen.normal]
  age:
    from : 5
    to : 6
  ghost:
    quantity: 2
    speed:
      from: 1
      to: 2 
7-10:
  _extends: [base,screen.normal]
  age:
    from : 7
    to : 10 
11-14:
  _extends: [base,screen.normal]
  age:
    from : 11
    to : 14
  ghost:
    quantity: 4
    speed:
      from: 1
      to: 4 
15-200:
  _extends: [base,screen.normal]
  age:
    from : 15
    to : 200
  ghost:
    quantity: 4
    speed:
      from: 1
      to: 4               