model:
  views:
    - name: default
  entities:
    - name: Basics
      abstract: true
      properties:
        - name: created
          type: dateTime
          default: now()
        - name: createdBy
          length: 50
    - name: LocCountries
      primaryKey:
        - iso3
      properties:
        - name: iso3
          length: 3
          required: true
        - name: name
          length: 60
          required: true
        - name: iso
          length: 2
          required: true
        - name: numericCode
          length: 5
          required: true
    - name: LocAreas
      primaryKey:
        - code
      properties:
        - name: code
          length: 16
          required: true
        - name: parentCode
          length: 16
        - name: countryCode
          length: 3
          required: true
        - name: type
          enum: AreaType
          length: 16
          required: true
        - name: name
          length: 200
          required: true
      relations:
        - name: country
          from: countryCode
          entity: LocCountries
          to: iso3
          target: areas
        - name: parent
          from: parentCode
          entity: LocAreas
          to: code
          target: children
    - name: LocAddresses
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          required: true
          autoIncrement: true
        - name: countryCode
          length: 3
          required: true
        - name: areaCode
          length: 16
          required: true
        - name: streetName
          length: 250
        - name: streetType
          enum: StreetType
          length: 3
        - name: streetNrFirst
          length: 20
        - name: zipCode
          length: 30
        - name: city
          length: 100
        - name: additionalData
          length: 100
      relations:
        - name: country
          from: countryCode
          entity: LocCountries
          to: iso3
        - name: area
          from: areaCode
          entity: LocAreas
          to: code
    - name: PmIndustryTypes
      primaryKey:
        - code
      properties:
        - name: code
          length: 30
          required: true
        - name: name
          length: 255
          required: true
    - name: PmParties
      extends: Basics
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          autoIncrement: true
        - name: type
          enum: PartyType
          length: 3
        - name: status
          enum: PartyStatus
          length: 12
          required: true
        - name: registeredDate
          type: dateTime
          default: now()
    - name: PmIdentifications
      extends: Basics
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          required: true
          autoIncrement: true
        - name: partyId
          type: integer
          required: true
        - name: type
          enum: IdentificationType
          length: 16
          required: true
        - name: value
          length: 100
          required: true
        - name: source
          length: 30
      relations:
        - name: party
          from: partyId
          entity: PmParties
          to: id
          target: identifications
    - name: PmContactMediums
      extends: Basics
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          required: true
          autoIncrement: true
        - name: partyId
          type: integer
          required: true
        - name: type
          enum: ContactMediumType
          length: 16
          required: true
        - name: value
          length: 100
        - name: isMain
          type: boolean
        - name: isFavorite
          type: boolean
        - name: source
          length: 30
        - name: createdBy
          length: 50
      relations:
        - name: party
          from: partyId
          entity: PmParties
          to: id
          target: contactMediums
    - name: PmIndividuals
      extends: Basics
      primaryKey:
        - partyId
      properties:
        - name: partyId
          type: integer
          required: true
        - name: gender
          enum: Gender
          length: 16
        - name: birthDate
          type: dateTime
        - name: deathDate
          type: dateTime
        - name: nationalityCode
          type: string
          length: 3
        - name: givenNames
          length: 200
        - name: middleNames
          length: 100
        - name: familyNames
          length: 100
        - name: legalName
          length: 500
      relations:
        - name: party
          type: oneToOne
          from: partyId
          entity: PmParties
          to: id
          target: individual
    - name: PmOrganizations
      extends: Basics
      primaryKey:
        - partyId
      properties:
        - name: partyId
          type: integer
          required: true
        - name: rootId
          type: integer
        - name: parentId
          type: integer
        - name: legalPeriodFrom
          type: dateTime
        - name: industryTypeCode
          length: 30
        - name: commercialDescription
          length: 400
        - name: tradingName
          length: 100
      relations:
        - name: party
          type: oneToOne
          from: partyId
          entity: PmParties
          to: id
          target: organization
        - name: parent
          from: parentId
          entity: PmOrganizations
          to: partyId
          target: children
        - name: root
          from: rootId
          entity: PmOrganizations
          to: partyId
          target: descendants
        - name: industryType
          from: industryTypeCode
          entity: PmIndustryTypes
          to: code
  enums:
    - name: AreaType
      values:
        - name: Country
          value: Country
        - name: Region
          value: Region
        - name: State
          value: State
        - name: Department
          value: Department
        - name: City
          value: City
    - name: StreetType
      values:
        - name: Street
          value: ST
        - name: Avenue
          value: AV
    - name: PartyType
      values:
        - name: Individual
          value: IND
        - name: Organization
          value: ORG
    - name: PartyStatus
      values:
        - name: Created
          value: CREATED
        - name: Active
          value: ACTIVE
        - name: InProgress
          value: IN_PROGRESS
        - name: Inactive
          value: INACTIVE
    - name: IdentificationType
      values:
        - name: NotAvailable
          value: NO DISPONIBLE
        - name: DNI
          value: DNI
        - name: RUC
          value: RUC
        - name: Passport
          value: PASAPORTE
        - name: CIP
          value: CIP
        - name: CE
          value: CE
        - name: CDI
          value: CDI
        - name: CTM
          value: CTM
        - name: CPP
          value: CPP
        - name: CIE
          value: CIE
        - name: CIRE
          value: CIRE
    - name: Gender
      values:
        - name: Male
          value: M
        - name: Female
          value: F
        - name: Undefined
          value: U
    - name: MaritalStatus
      values:
        - name: Married
          value: CASADO
        - name: Divorced
          value: DIVORCIADO
        - name: Single
          value: SOLTERO
        - name: Widower
          value: VIUDO
        - name: Concubinage
          value: CONCUBINATO
        - name: Separation
          value: SEPARACION
        - name: Undefined
          value: UNDEFINED
    - name: ContactMediumType
      values:
        - name: Phone
          value: Phone
        - name: CellPhone
          value: CellPhone
        - name: SecondaryPhone
          value: SecondaryPhone
        - name: WorkPhone
          value: WorkPhone
        - name: Email
          value: Email
        - name: WorkEmail
          value: WorkEmail
        - name: Twitter
          value: Twitter
        - name: Instagram
          value: Instagram
        - name: Facebook
          value: Facebook
        - name: Skype
          value: Skype
        - name: MainMobile
          value: MainMobile
        - name: MainPhone
          value: MainPhone
        - name: SecPhone
          value: SecPhone
data:
  sources:
    - name: locations
      mapping: default
      dialect: MySQL
      connection: ${CNX_LOCATIONS}
    - name: parties
      mapping: default
      dialect: MySQL
      connection: ${CNX_PARTIES}
    - name: ledgerAccounts
      mapping: default
      dialect: MySQL
      connection: ${CNX_LEDGER_ACCOUNTS}
    - name: debtors
      mapping: default
      dialect: MySQL
      connection: ${CNX_DEBTORS}
    - name: insights
      mapping: default
      dialect: PostgreSQL
      connection: ${CNX_INSIGHTS}
  stages:
    - name: default
      sources:
        - name: locations
          condition: entity.startWith("Loc")
        - name: parties
          condition: entity.startWith("Pm")
        - name: ledgerAccounts
          condition: entity.startWith("Lam")
        - name: debtors
          condition: entity.startWith("Db")
    - name: insights
      sources:
        - name: insights
    - name: cqrs
      sources:
        - name: insights
          condition: action == "select"
        - name: locations
          condition: entity.startWith("Loc")
        - name: parties
          condition: entity.startWith("Pm")
        - name: ledgerAccounts
          condition: entity.startWith("Lam")
        - name: debtors
          condition: entity.startWith("Db")
  mappings:
    - name: default
      entities:
        - name: Basics
          abstract: true
          properties:
            - name: created
              mapping: created
            - name: createdBy
              mapping: created_by
        - name: LocCountries
          mapping: tbl_loc_countries
          properties:
            - name: iso3
              mapping: iso3
            - name: name
              mapping: name
            - name: iso
              mapping: iso
            - name: numericCode
              mapping: numeric_code
        - name: LocAreas
          mapping: tbl_loc_areas
          properties:
            - name: code
              mapping: code
            - name: parentCode
              mapping: parent
            - name: countryCode
              mapping: country
            - name: type
              mapping: type
            - name: name
              mapping: name
        - name: LocAddresses
          mapping: tbl_loc_addresses
          properties:
            - name: id
              mapping: id
            - name: countryCode
              mapping: country
            - name: areaCode
              mapping: area
            - name: streetName
              mapping: street
            - name: streetType
              enum: StreetType
              mapping: street_type
            - name: streetNrFirst
              mapping: nro
            - name: zipCode
              mapping: zip_code
            - name: city
              mapping: city
            - name: additionalData
              mapping: additional_data
        - name: PmIndustryTypes
          mapping: tbl_pm_industry_types
          properties:
            - name: code
              mapping: code
            - name: name
              mapping: name
        - name: PmParties
          extends: Basics
          mapping: tbl_pm_party
          properties:
            - name: id
              mapping: id
            - name: type
              mapping: type
            - name: status
              mapping: status
            - name: registeredDate
              mapping: registered_date
        - name: PmIdentifications
          extends: Basics
          mapping: tbl_pm_identifications
          properties:
            - name: id
              mapping: id
            - name: type
              mapping: type
            - name: value
              mapping: value
            - name: partyId
              mapping: party_id
            - name: source
              mapping: source
        - name: PmContactMediums
          extends: Basics
          mapping: tbl_pm_contract_mediums
          properties:
            - name: id
              mapping: id
            - name: partyId
              mapping: party_id
            - name: type
              mapping: type
            - name: value
              mapping: value
            - name: isMain
              mapping: is_main
            - name: isFavorite
              mapping: is_favorite
            - name: source
              mapping: source
        - name: PmIndividuals
          extends: Basics
          mapping: tbl_pm_individuals
          properties:
            - name: partyId
              mapping: party_id
            - name: gender
              enum: Gender
              mapping: gender
            - name: birthDate
              mapping: birth_date
            - name: deathDate
              mapping: death_date
            - name: nationalityCode
              mapping: nationality
            - name: givenNames
              mapping: given_names
            - name: middleNames
              mapping: middle_names
            - name: familyNames
              mapping: family_names
            - name: legalName
              mapping: legal_name
        - name: PmOrganizations
          extends: Basics
          mapping: tbl_pm_organizations
          properties:
            - name: partyId
              mapping: party_id
            - name: legalPeriodFrom
              mapping: legal_period_from
            - name: tradingName
              mapping: trading_name
            - name: industryTypeCode
              mapping: industry_type
            - name: commercialDescription
              mapping: commercial_description
    - name: oracle
      extends: default
      entities:
        - name: LocCountries
          sequence: sq_loc_countries
        - name: LocAreas
          sequence: sq_loc_areas
        - name: LocAddresses
          sequence: sq_loc_addresses
        - name: PmIndustryTypes
          sequence: sq_pm_industry_types
        - name: PmParties
          sequence: sq_pm_parties
        - name: PmIdentifications
          sequence: sq_pm_identifications
        - name: PmContactMediums
          sequence: sq_pm_contact_mediums
        - name: PmIndividuals
          sequence: sq_pm_individuals
        - name: PmOrganizations
          sequence: sq_pm_organizations
app:
  host: $HOST
  port: $PORT
  listeners:
    - name: syncInsights
      actions:
        - insert
        - bulkInsert
        - update
        - delete
      condition: options.stage.in("default","cqrs")
      after: sendMessage("insights-sync",[{expression:expression,data:data}])
  kafka:
    config: $KAFKA_CONFIG
