screen:
   width: 1800
   high: 1200
   map : |
     ######################################################
     #.*..........#..........*.##.*..........#..........*.#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #.........................##.........................#
     #.####.#.#########.#.####.##.####.#.#########.#.####.#
     #......#.....#.....#......##......#.....#.....#......#
     ######.#####.#.#####.############.#####.#.#####.######
          #.#           #.#          #.#           #.#     
          #.# ###  #### #.#          #.# ###  #### #.#     
     ######.# #  A  A # #.############.# #  A  A # #.######
          .  #       #  .            .  #       #  .      
     ######.# #  A  A # #.############.# #  A  A # #.######
          #.# ######### #.#          #.# ######### #.#     
          #.#     >     #.#          #.#           #.#     
     ######.# ######### #.############.# ######### #.######
     #............#............##............#............#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #...##...............##...##...##...............##...#
     ###.##.#.#########.#.##.######.##.#.#########.#.##.###
     #......#.....#.....#......##......#.....#.....#......#
     #.##########.#.##########.##.##########.#.##########.#
     #.*.....................*.##.*.....................*.#
     ######################### ## #########################
     #.*..........#..........*.##.*..........#..........*.#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #.........................##.........................#
     #.####.#.#########.#.####.##.####.#.#########.#.####.#
     #......#.....#.....#......##......#.....#.....#......#
     ######.#####.#.#####.############.#####.#.#####.######
          #.#           #.#          #.#           #.#     
          #.# ###  #### #.#          #.# ###  #### #.#     
     ######.# #  A  A # #.############.# #  A  A # #.######
          .  #       #  .            .  #       #  .      
     ######.# #  A  A # #.############.# #  A  A # #.######
          #.# ######### #.#          #.# ######### #.#     
          #.#           #.#          #.#           #.#     
     ######.# ######### #.############.# ######### #.######
     #............#............##............#............#
     #.####.#####.#.#####.####.##.####.#####.#.#####.####.#
     #...##...............##...##...##...............##...#
     ###.##.#.#########.#.##.######.##.#.#########.#.##.###
     #......#.....#.....#......##......#.....#.....#......#
     #.##########.#.##########.##.##########.#.##########.#
     #.*.....................*.##.*.....................*.#
     ######################################################