screen:
  width: 1200
  high: 800
  map : | 
      ###########################
      #.........................#
      #.####.#.#########.#.####.#
      #......#.....#.....#......#
      ######.#####.#.#####.######
          #.#           #.#     
          #.#           #.#     
      ######.# ######### #.######
      #........>...#............#
      #.####.#####.#.#####.####.#
      #...##...............##...#
      ###.##.#.#########.#.##.###
      #......#.....#.....#......#
      #.##########.#.##########.#
      #.*.....................*.#
      ###########################