name: Publish
on:
  push:
    branches: [release/*]
  pull_request:
    branches: [release/*]
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install global dependencies
        run: npm install -g grunt-cli husky
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run dist
      - name: Config
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - name: Publish
        run: cd ./dist && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Delete branch
      #   run: |
      #     git push origin --delete ${{ github.ref_name }} --no-verify
      #     echo "Branch ${{ github.ref_name }} deleted"        


