name: Unit Test
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install global dependencies
        run: npm install -g grunt-cli husky
      - name: Install dependencies
        run: npm install
      - name: unit test
        run: npm run test      
